### ISSUE TITLE
How to generate the blured kernel and the LR image x'

### ISSUE THREAD

**Issue by sdlpkxd** [IVRL/KMSR#1]
Hi, thanks for your work.

I'm confused by the generation process of blured kernel and LR Image x'.
 In the paper, you generated x' using unknown blured kernel, but the blured kernel is unknown, to get the unknown blured kernel, you used the LR image x', but we can not get the x' if we did not know the blured kernel. 

So, the blured kernel and the LR image is both unknown, how do you overcome this, or do I misunderstanding?

**Comment by zrfanzy** [comment]
Hi,

Did you read Section 3.2 in our paper, I think it should explain how we get a bunch of kernels.
Please let me know if it's still not clear.

**Comment by sdlpkxd** [comment]
I read the Section 3.2,  you generated blured kernel using LR image x‘, then you just use the Gan net to get more kernels, didn't you ? But In Section 3.1 you got the LR image x‘ using blured kernel. 

The kernel in 3.1 is the same with kernel in 3.2  and the LR image x' in 3.1 is the same with LR image x' in 3.2, I'm right ?

**Comment by sdlpkxd** [comment]
If the blured kernel is not generated,  how can we get LR image x' ?

**Comment by zrfanzy** [comment]
> If the blured kernel is not generated, how can we get LR image x' ?

Hi, 
in the paper, we use the notation x' to present LR image, this LR image can either be the real LR image (e.g., taken by a low-end camera), or synthetic LR image (generated by applying a blur kernel on an HR image)

For 3.2.1, we use part of the DPED dataset [1] as LR image x' to estimate k'
later in 3.3, we use DIV2K dataset [2] as HR image y with the kernels estimated and generated in the previous step to generate the x' for training

These were explained in 4.1.

Hope it's helpful.

references:
[1] Andrey Ignatov, Nikolay Kobyshev, Radu Timofte, KennethVanhoey, and Luc Van Gool.  DSLR-quality photos on mobile devices with deep convolutional networks.
[2] Radu  Timofte,  Eirikur  Agustsson,  Luc  Van  Gool,  Ming-Hsuan Yang, Lei Zhang, Bee Lim, et al.  NTIRE 2017 challenge on single image super-resolution: Methods and results.

**Comment by sdlpkxd** [comment]
Got it.
Thank you very much for your datiled reply.

**Comment by zrfanzy** [comment]
Cool! Then I close the issue :)

**Comment by hcleung3325** [comment]
> I read the Section 3.2, you generated blured kernel using LR image x‘, then you just use the Gan net to get more kernels, didn't you ? But In Section 3.1 you got the LR image x‘ using blured kernel.
> 
> The kernel in 3.1 is the same with kernel in 3.2 and the LR image x' in 3.1 is the same with LR image x' in 3.2, I'm right ?

Hello sdlpkxd.
I also get the same question when I wanna estimate the kernel.
May I know what x' refers to? In the paper, x' refers to bicubic-upscaled LR image or coarsely HR image.
Is that the image x' that input to the estimator should be the LR patch from dataset, such as Div2k LR bicubic downsampling set?
Previously, I misunderstand the paper and input the HR patch 512x512 to the estimator.
After that, I convoluted this generated kernel with Div2k HR to generate LR x' for SR training.
End-up, the result is not satisfactory.
May be this is the problem > <
